version: 0.2

phases: 
  install:
    commands:
      - echo Build started on `date`
      - echo "Compiling"
      - go test gotests/
  pre_build:
    commands:
      - 
      -
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - test
    - '**/*'
  discard-paths: no