version: 0.2

env:
  variables:
    SRC_DIR: /src/github.com/KhoiMVu/CI-testing
    GIT_REPO: github.com/KhoiMVu/CI-testing
    #S3_BUCKET:

phases: 
  install:
    commands:
      - pwd
      - ls
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH

      - echo Build started
      - echo "Running go tests"
      - go test ${GIT_REPO}/gotests/
      - echo Creating Binaries
      - go install ${GIT_REPO}/gotests/
      #- go build ${GIT_REPO}/gotests/sum.go
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      #- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      #- go get github.com/TrustedKeep/kmip
  pre_build:
    commands:
      - echo "Running binary 'gotests'"
      - go run gotests/sum.go
      - echo *******Info
      - pwd
      - echo $GOPATH
      - ls -l
  post_build:
    commands:
      - echo Build completed

# artifacts:
#   files:
#     - gotests
#     #- sum
#   discard-paths: no