version: 0.2

phases: 
  install:
    commands:
      - echo Build started
      - echo "Running go tests"
      - go test gotests/
      - echo Creating Binaries
      - go install gotests
      - go build gotests/sum.go
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - go get github.com/TrustedKeep/kmip
  pre_build:
    commands:
      - echo "Running binary 'gotests'"
      - go run gotests/sum.go
      - echo *******Info
      - pwd
      - echo $GOPATH
      - ls -l
      - dep init
      - dep ensure
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - gotests
    - sum
  discard-paths: no